# Generated by Django 5.0.1 on 2024-02-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название меню')),
                ('slug', models.SlugField(max_length=100, verbose_name='Слаг')),
                ('is_leaf', models.BooleanField(default=True, verbose_name='Является самым нижним уровнем меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='draw_menu.menumodel', verbose_name='Меню верхнего уровня')),
            ],
        ),
    ]
