# Generated by Django 5.0.1 on 2024-02-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_menu', '0003_headmenumodel_menuitemmodel_delete_menumodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='headmenumodel',
            name='slug',
            field=models.SlugField(max_length=100, null=True, verbose_name='Слаг'),
        ),
    ]
